export const SET_SONG_RESULTS = "SET_SONG_RESULTS";
export const LOADING = "LOADING";
export const CLEAR_ALL = "CLEAR_ALL";
export const SET_CURRENT_SONG = "SET_CURRENT_SONG";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SAVED_SONGS = "SET_SAVED_SONGS";
